services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: art
      POSTGRES_PASSWORD: art
      POSTGRES_DATABASE: art
  app:
    ports:
      - 8080:8080
    build: .
    environment:
      DISCORD_TOKEN: $DISCORD_TOKEN # Loaded from the .env file
      ADMINISTRATION_PASSWORD: $ADMINISTRATION_PASSWORD

      SPRING_PROFILES_ACTIVE: 'production'

      GUILD_ID: 683633975838769192 # ID of the managed guild
      ART_CHANNEL_ID: 683638355895779450 #gartic-art
      REPOST_CHANNEL_ID: 683633975842963456 #chat
      REPOST_INTERVAL: 1440 # 24 hours (the value is in minutes)
    depends_on:
      - database